[tool.black]
line-length = 88  # Default
target-version = ['py312']
include = '\.pyi?$'
# If you need to exclude certain directories:
# exclude = '/\.git|\.mypy_cache|\.venv/'

[tool.isort]
profile = "black"  # Makes isort compatible with Black
line_length = 88
multi_line_output = 3

[tool.flake8]
exclude = [
    ".git",
    "__pycache__",
    "build",
    "dist",
    ".venv",
    "node_modules"
]