version: "3.8"

services:
  agents:
    image: lachsbagel/moragents_dockers-agents:amd64-0.2.0
    build:
      dockerfile: Dockerfile
      context: ./agents
    ports:
      - "8080:5000"
    restart: always
    volumes:
      - agents_data:/var/lib/agents
      - ./agents/src:/app/src
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - BASE_URL=http://host.docker.internal:11434
      - OLLAMA_HOST=host.docker.internal  
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
    network_mode: "bridge"

  nginx:
    image: lachsbagel/moragents_dockers-nginx:amd64-0.2.0
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: nginx
    ports:
      - "3333:80"

volumes:
  agents_data:

networks:
  default:
    driver: bridge

