name: Deploy MySuperAgent Infrastructure

on:
  # Only run on specific branch and path conditions
  push:
    branches:
      - main # Only on the main branch
    paths:
      - "infrastructure/mysuperagent-stack.yml" # Only when this file changes

  # Allow manual triggering through GitHub UI
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - production

# Don't run on PRs or other events
# (absence of 'pull_request' in triggers means it won't run on PRs)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --template-file infrastructure/mysuperagent-stack.yml \
            --stack-name mysuperagent-stack-${{ github.event.inputs.environment || 'staging' }} \
            --capabilities CAPABILITY_IAM \
            --no-fail-on-empty-changeset
