# .github/workflows/lint.yml
name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install linting tools
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black isort

      - name: Run Python linters
        run: |
          # Run linters on Python files
          black --check .
          isort --check .
          flake8 .

      - name: Run JavaScript/TypeScript linters
        run: |
          # Install JS linting dependencies if package.json exists
          if [ -f package.json ]; then
            npm ci
            # Run eslint if configured in package.json
            if grep -q '"eslint"' package.json; then
              npm run lint
            fi
          fi
