name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install linting tools
        run: |
          python -m pip install --upgrade pip
          pip install flake8==7.0.0 black==23.12.1 isort==5.13.2

      - name: Run Black with diff output
        run: |
          # Run black on Python files with diff output
          # Use line-length=120 to match pyproject.toml
          black --diff --line-length=120 .

      - name: Check formatting with Black
        run: |
          # Check if files are properly formatted
          # Use line-length=120 to match pyproject.toml
          black --check --line-length=120 .

      - name: Run isort with diff output
        run: |
          # Run isort with diff output
          isort --diff .

      - name: Check imports with isort
        run: |
          # Check if imports are properly sorted
          isort --check .

      - name: Run flake8
        run: |
          # Run flake8 for other linting checks with comprehensive exclusions
          flake8 . --exclude=.git,__pycache__,build,dist,*.egg,*.egg-info,.eggs,.venv,venv,env,.env,ENV,node_modules,*/node_modules/*,*/.venv/*,*/site-packages/*

      - name: Run JavaScript/TypeScript linters
        run: |
          # Install JS linting dependencies if package.json exists
          if [ -f package.json ]; then
            npm ci
            # Run eslint if configured in package.json
            if grep -q '"eslint"' package.json; then
              npm run lint
            fi
          fi
