name: MOR Agents Build Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # remove this - only for testing

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Build with PyInstaller
      run: pyinstaller --onedir --windowed --icon=images/moragents.ico --name=MORagents main.py

    - name: Install Inno Setup
      run: choco install innosetup -y

    - name: Compile Inno Setup Script
      run: |
        iscc /O".\MORagentsWindowsInstaller" "MORagents_setup.iss"

    - name: Upload Installer
      uses: actions/upload-artifact@v2
      with:
        name: MORagentsSetup
        path: .\MORagentsWindowsInstaller\MORagentsSetup.exe
