name: Python Tests

on:
  push:
    branches: [main]
    paths:
      - "submodules/agents/**" # Only run when changes in this path
  pull_request:
    branches: [main]
    paths:
      - "submodules/agents/**" # Only run when changes in this path
  workflow_dispatch: # Allow manual triggering

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive # Make sure we get the submodules too

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12" # Updated to 3.12 based on your lint workflow

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.7.1 # Updated to a more recent version
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Cache Poetry dependencies
        uses: actions/cache@v3
        with:
          path: submodules/agents/.venv
          key: ${{ runner.os }}-poetry-${{ hashFiles('submodules/agents/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install dependencies
        run: |
          cd submodules/agents
          poetry install --no-interaction

      - name: Run tests
        run: |
          cd submodules/agents
          poetry run python -m pytest
